######################################################################################################
# Rasa and Rasa Actions docker-compose for Azure Pipelines container building                        #
######################################################################################################

version: '3.0'
services:
  rasa:
    build:
      context: ./rasa
      args:
        RASA_IMAGE: '${IMAGES_CURRENT_RASA}'
    container_name: botfront-rasa
    networks:
      - botfront-network
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - models:/app/models
     
  actions:
    build:
      context: ./actions
      dockerfile: Dockerfile.production
      args:
        RASA_SDK_IMAGE: '${IMAGES_CURRENT_ACTIONS}'
    container_name: botfront-actions
    networks:
      - botfront-network
    restart: always
    ports:
      - '5055:5055'
    volumes:
      - './actions:/app/actions'
    command:
      - start
      - '--actions'
      - actions

networks:
  botfront-network: {}
volumes:
  models: