######################################################################################################
# Rasa and Rasa Actions docker-compose for local use                                                 #
######################################################################################################

version: '3.0'
services:
  rasa:
    build:
      context: ./rasa
      args:
        RASA_IMAGE: '${IMAGES_CURRENT_RASA}'
    container_name: botfront-rasa
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - models:/app/models
    env_file:
      - .env
  actions:
    build:
      context: ./actions
      args:
        RASA_SDK_IMAGE: '${IMAGES_CURRENT_ACTIONS}'
    container_name: botfront-actions
    restart: always
    ports:
      - '5055:5055'
    volumes:
      - './actions:/app/actions'
    command:
      - start
      - '--debug'
      - '--actions'
      - actions
    env_file:
      - .env
volumes:
  models: