apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: actions
  name: actions
spec:
  ports:
  - name: "5055"
    port: 5055
    targetPort: 5055
  selector:
    io.kompose.service: actions
status:
  loadBalancer: {}
