apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: actions
  name: actions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actions
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: actions
    spec:
      containers:
      - args:
        - start
        - --actions
        - actions
        env:
        - name: BF_URL
          value: http://botfront.default.svc.cluster.local:3000/graphql
        - name: RASA_ACTIONS_SERVICE_RECOMMENDER_ENDPOINT
          value: http://service-match-engine.default.svc.cluster.local:80
        image: __dockerregistryname__.azurecr.io/rasaplatform_actions:__tag__
        imagePullPolicy: Always
        name: actions
        ports:
        - containerPort: 5055
        livenessProbe:
          httpGet:
            path: /health
            port: 5055
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 10
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
