apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileshare-botfront-models
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azurefilesharesecret
    secretNamespace: default
    shareName: __azurefilesharebotfrontmodels__
    readOnly: false