apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileshare-botfront-models-dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azurefilesharesecret
    secretNamespace: default
    shareName: __azurefilesharebotfrontmodelsdev__
    readOnly: false